### ISSUE TITLE
Customize polymode objects

### ISSUE THREAD

**Issue by lionel-** [vspinu/polymode#58]
Hello,

I would like to remove the background font adjustment of code chunks.

From looking at the code the `adjust-face` method looks relevant for this but I am not sure how those eieio objects work. I guess it's not a simple matter of setting a customization variable?

**Comment by vspinu** [comment]
Completely remove it? Or make less sharp?

Something like this should have worked: 

```
(eval-after-load "polymode-classes"
  '(progn
     (oset-default pm-hbtchunkmode :adjust-face nil)))
```

But for some peculiar reason it doesn't. So class customization in eieio is kinda useless right now.

It seems that at this stage the only way  to fix it is to set it by specific inner modes like this:

```
(oset pm-inner/noweb+R :adjust-face nil)
(oset pm-inner/markdown :adjust-face nil)
```
Not having the highlight might be confusing. So you might simply want to set it to less than the default 2.

**Comment by lionelgit** [comment]
Thanks Vitalie, it works.

I'd like to set it to `nil` because my color theme uses backgrounds to highlight keywords and the polymode dimming overwrites them.

To keep things readable, I adjusted the font used in the fundamental innermode to highlight the ```` ```{r} ``` ```` things. Currently this follows the `font-lock-type-face`, but it'd be useful if it used a custom poly-mode face.

And many thanks for polymode, it's very useful!

**Comment by lionelgit** [comment]
>  it'd be useful if it used a custom poly-mode face.

Even better would be two faces, one for the opening of the chunk, and the other for the closing. This way we could overline the opening and underline the closing and it would be clear what is a chunk and what is not, even without the background dimming.

**Comment by vspinu** [comment]
> I'd like to set it to nil because my color theme uses backgrounds to highlight keywords and the polymode dimming overwrites them.

Hm. That's not good then. Then polymode should not affect those regions with non default background. 

You need not set it to nil. You can set it to a face, number or a list of font properties. Se the documentation of pm-hbtchunkmode.

> Even better would be two faces, one for the opening of the chunk, and the other for the closing. 

There are `:head-adjust-face` and `:tail-adjust-face` slots in each `hbtchunkmode` object. You can set those to whatever face you want but be aware that head and tail can have it's own mode and you will be overwriting that mode. This is why I think the default settings that work by dimming/lightning the background should work the best.

For example:

```
(oset pm-inner/markdown :head-adjust-face 'font-lock-constant-face)
```

**Comment by vspinu** [comment]
Hi lionel, I wonder if I can close this one. I think there have been a number of changes on this one since you opened the issue. The chunk fontification should not interfere with whatever custom themes are installed. It just dims or lightens it proportionally by adjusting the background of all fonts within the chunk.

**Comment by lionel-** [comment]
yes I just use the regular dimming nowadays.

The new fontification and Evil integration seem to work really well, thanks a lot for this nice work Vitalie!
