### ISSUE TITLE
poly-markdown+r-mode doesn't like ESS evaluation commands?

### ISSUE THREAD

**Issue by crowding** [vspinu/polymode#6]
Open an .Rmd file and type in

    testing...
    
    ```R
    x <- function() {
      1
    }
    ```

Position cursor in the function and type C-c C-c, C-c C-p, or such. It tries to evaluate the lines with the backticks along with the lines belonging to the function.

**Comment by plantarum** [comment]
I encountered a related issue trying to evaluate functions from within fenced code blocks. The backticks in the fences, or apostrophes in the preceding markdown chunk, will make ESS think it is inside a string, and so refuse to evaluate the code. A possible approach to fixing this issue, and the one that @crowding raised, is the following advice:

~~~~{lisp}
(defun pm-ess-limit-eval-to-chunk (orig-fun &rest args)
  "Wrapper for ess-eval-functions.
Without this, apostrophes in the preceding text chunk cause
ess-mark-function, ess-send-function to fail, thinking they are inside a
string. Similarly, ess-eval-paragraph gets confused by the fence rows."
  (interactive)
  (let (res)
    (if (poly-markdown+r-mode)
        (save-restriction
          (pm/narrow-to-span)
          (setq res (apply orig-fun args))))
    res))

(advice-add 'ess-beginning-of-function :around #'pm-ess-limit-eval-to-chunk)
(advice-add 'ess-eval-paragraph :around #'pm-ess-limit-eval-to-chunk)
~~~~

Since this code will only modify the behaviour of the functions in question from within polymode, it *should* be safe to apply generally. However, there may be better solutions than global advice? If not, I can wrap this up in a pull request.
