### ISSUE TITLE
innermodes with symmetric anchors

### ISSUE THREAD

**Issue by lionel-** [vspinu/polymode#60]
Hello,

Is it possible to define innermodes with symmetric head and tail regexps?

I am trying to implement a Markdown+YAML polymode but I can't get it to work. The goal is to capture the YAML configuration of Pandoc files, which are delimited by a `---` header and footer.

```lisp
(defcustom pm-inner/markdown+yaml
          (pm-hbtchunkmode "markdown+yaml"
                           :mode 'yaml-mode
                           :head-reg "^---"
                           :tail-reg "^---")
          "YAML header in Markdown files"
          :group 'innermodes
          :type 'object)
```

I also noticed that `poly-markdown-mode` does not recognize 'anonymous' code blocks such as
````
 ```
 anonymous chunk
 ```
````
So I guess it's a limitation in poly-mode that it can't work with symmetric anchors? Or am I missing something?

**Comment by vspinu** [comment]
Symmetric markes are really bad idea because to correctly parse those you will need to re-parse the whole file each time you need it. In case of a yaml it's easier as you know that it's located in the begining of the file. There is a [markdowsn+R+yaml](https://github.com/vspinu/polymode/blob/master/img/rapport.png) implementation.

`:head-reg` and `:head-tail` could be functions. See  for example how [`R+C++`](https://github.com/vspinu/polymode/blob/master/modes/poly-R.el#L138-L169) is defined.

**Comment by lionel-** [comment]
Thanks. I just solved this particular problem because Pandoc also accepts a `...` footer for YAML chunks.

It's still bad news for the "anonymous" markdown code chunks though :/

**Comment by lionel-** [comment]
Thanks for pointing out that headers are by definition not completely symmetric. We can use the "beginning of buffer" special character to correctly match this kind of symmetric anchors:
```lisp
:head-reg "\\`---"
:tail-reg "[^\\`]---")
```

**Comment by lionel-** [comment]
Another important use-case for symmetric marks: inline math. I need to duplicate a lot of Auctex configuration to make typing math in Markdown convenient.
