### ISSUE TITLE
compilation error and warning in polymode-20150723.156

### ISSUE THREAD

**Issue by nrnrnr** [vspinu/polymode#69]
While installing using MELPA, got this error:

````
Compiling file /home/nr/.emacs.d/elpa/polymode-20150723.156/poly-slim.el at Tue Jul 28 13:14:54 2015
poly-slim.el:4:1:Error: Cannot open load file: no such file or directory, scss-mode
````

and this one

````
Compiling file /home/nr/.emacs.d/elpa/polymode-20150723.156/polymode-methods.el at Tue Jul 28 13:14:54 2015
polymode-methods.el:75:62:Warning: `class-of' is an obsolete function (as of
    24.4); use `eieio-object-class' instead.
polymode-methods.el:121:49:Warning: `object-name-string' is an obsolete
    function (as of 24.4); use `eieio-object-name-string' instead.
````

**Comment by vspinu** [comment]
@siassaj I think we have a problem. We want this to work with MELPA but we don't want to pull all possible dependences like `scss-mode`, `coffee-mode`, `slim-mode` etc.

The problem should have also occured with poly-markdown. But no-one noticed it so far because people usually have markdown already installed. 

Eventually we must create separate packages for each polymode bundle (poly-slim, poly-R etc) and add all ELPA relevant dependences in each of them. For now I am commenting out all the requires. Those are not necessary for compilation.

**Comment by siassaj** [comment]
Hrm I didn't notice, should have known better

**Comment by Toxaris** [comment]
> Eventually we must create separate packages for each polymode bundle (poly-slim, poly-R etc) and add all ELPA relevant dependences in each of them

Yes that would be better!

Or the documentation should at least explain that packages that use `polymode` should add the relevant dependencies. See the jekyll-modes issue referenced above.
