### ISSUE TITLE
polymode for julia

### ISSUE THREAD

**Issue by gragusa** [vspinu/polymode#96]
I am trying to set up polymode for [julia](www.julialang.org). ESS has a mode for it `ess-julia-mode`. 

That's what I came up with 

```
(require 'polymode)
(require 'poly-markdown)

(defcustom pm-poly/julia
  (pm-polymode-one "julia"
                   :hostmode 'pm-host/julia
                   :innermode 'pm-inner/fundamental)
  "julia root polymode. Not intended to be used directly."
  :group 'polymodes
  :type 'object)

(defcustom pm-inner/markdown+julia
  (clone pm-inner/markdown
         :mode 'ess-julia-mode)
  "Markdown for julia"
  :group 'innermodes
  :type 'object)

(define-polymode poly-markdown+julia-mode pm-poly/markdown :lighter " PM-jmd")
```

I added the following to `.emacs`

```
(add-to-list 'auto-mode-alist '("\\.[jJ]md" . jmd-mode))
(defun jmd-mode ()
        "ESS Markdown mode for jmd files"
        (interactive)
        (require 'poly-julia)
        (require 'poly-markdown)
        (ess-julia-mode)
        (poly-markdown+julia-mode))
      )
```

But when I try to open a `.jmd` file I get an error: `Required feature poly-mode not provided`.

Any help with this will be appreciated.

**Comment by vspinu** [comment]
Your definition is incorrect. Everything except the last line is not needed:

```
(define-polymode poly-markdown+julia-mode pm-poly/markdown :lighter " PM-jmd")
(add-to-list 'auto-mode-alist '("\\.[jJ]md" . poly-markdown+julia-mode))
```
will work. Just the following will also work:

```
(add-to-list 'auto-mode-alist '("\\.[jJ]md" . poly-markdown-mode))
````

Your `jmd-mode` is not doing the right thing because it tries to install `ess-julia-mode` which is meaningless in md files.

markdown blocks with `'''julia` will work fine. In order to get `ess-julia` you would need to have a `'''ess-julia` header. Having a way to remap from arbitrary names to mode names is not implemented yet but I am looking into it right now.  Also the dash in `ess-julia` does cause some problems. I am also looking into it right now. Will be back with you shortly.

**Comment by vspinu** [comment]
All issues fixed. The following should do the trick:

```
(add-to-list 'auto-mode-alist '("\\.[jJ]md" . poly-markdown-mode))
(add-to-list 'polymode-mode-name-override-alist '(julia . ess-julia))
```

Thanks for the report.

**Comment by gragusa** [comment]
Thanks it works great! But there is a catch. Your code rely on `alist-get` which is only available in `emacs 25`. I had to add the definition form [here](https://github.com/emacs-mirror/emacs/blob/master/lisp/subr.el#L592).

**Comment by vspinu** [comment]
Ah. Sorry. Changin it now.

**Comment by gragusa** [comment]
Terrific. Thanks.
